In [1]:
import numpy as np

In [83]:
N = 10

Задание 1

In [84]:
x = list(range(0, N))
x.reverse()
x = np.array(x)

In [85]:
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2

In [86]:
y = np.diag(x, k=0)
y

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [87]:
y.sum()

45

Задание 3

In [88]:
'''4x + 2y + z = 4
   x + 3y = 12
   5y + 4z = -3'''

'4x + 2y + z = 4\n   x + 3y = 12\n   5y + 4z = -3'

In [98]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

In [100]:
from numpy import linalg

In [101]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [102]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Задание 4

In [105]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [108]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [133]:
def similer_customer(users_stats, next_user_stats):
    cosines = []
    i = 1
    for custom in users_stats:
        user = []
        cosine = np.dot(next_user_stats, custom) / (np.linalg.norm(next_user_stats) * np.linalg.norm(custom))
        user.append(cosine)
        user.append(i)
        cosines.append(user)
        i += 1
    user_id = sorted(cosines)[-1][1]
    cosine_similarity = sorted(cosines)[-1][0]
    return user_id, cosine_similarity

In [134]:
similer_customer(users_stats, next_user_stats)

(8, 0.9486832980505138)